spring.datasource.url=jdbc:h2:mem:portfolio_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true

server.port=8081

# Google Gemini API Key
spring.ai.google.genai.api-key=AIzaSyD9okGApPhdNlZghYTNl8wYECNlW7qXcDk
# Optional: default model to use
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.retry.max-attempts=3
spring.ai.retry.backoff.initial-interval=1000
spring.ai.retry.backoff.multiplier=2